language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
deploy:
  provider: npm
  email: Oliver_web@163.com
  api_token: "$NPM_TOKEN"
  cleanup: true
  on:
    branch: master
